#!/bin/bash
# script to create pi-gpio deb

# 2022-08-04 use install, include HEADERS
# 2022-08-10 update HEADERS MANPAGES
# 2022-09-10 select dist directory
# 2022-12-02 Install python overlay
# 2022-12-12 REVISION
# 2022-12-23 /usr/lib/python3/dist-packages/
# 2022-12-24 gpioStatus
# 2023-09-11 pi-gpiod
# 2023-09-13 pi_sock.py
# 2023-09-14 pi_sock.lib
# 2024-02-28 added kpwm

# Directory containing code source
# Edit if not default
LIBNAME='pi-gpio'
CODEDIR="$HOME/$LIBNAME"
SOURCE="$CODEDIR/source"

# Select destination directory for deb
# default is 'dist' under $CODEDIR
DISTDIR="$CODEDIR/dist"
# Check/create DISTDIR
if [ ! -e $DISTDIR ]; then
	mkdir $DISTDIR
fi

ARCH=$(dpkg --print-architecture)
# if [[ $(uname -m) == "aarch64" ]]; then
# 	ARCH='arm64'
# else
# 	ARCH='armhf'
# fi

REVISION="$1"
if [ "${REVISION}" = "" ]; then
REVISION="1"
fi

VERS=$(cat $CODEDIR/VERSION)
DEB_VERSION="$VERS-$REVISION"

# Rebuild library files
CURRENT_DIR=$(pwd)
cd $SOURCE
make clean
make
cd $CURRENT_DIR

DYNAMIC="lib$LIBNAME.so.$VERS"
DEB_DIR_NAME="${LIBNAME}_${DEB_VERSION}_$ARCH"
DEB_DIR="$DISTDIR/$DEB_DIR_NAME"

# Make DEB structure
mkdir -p $DEB_DIR
# Remove any existing content
rm -rf $DEB_DIR/*

mkdir -p $DEB_DIR/usr/lib
mkdir -p $DEB_DIR/usr/include
mkdir -p $DEB_DIR/usr/share/man/man3
mkdir -p $DEB_DIR/DEBIAN
mkdir -p $DEB_DIR/usr/lib/python3/dist-packages/
mkdir -p $DEB_DIR/usr/bin

# Copy libraries
echo "Copy libraries"
cp $SOURCE/$DYNAMIC $DEB_DIR/usr/lib/

cp $SOURCE/libpi-sock.so.$VERS $DEB_DIR/usr/lib/
ln -sfr $DEB_DIR/usr/lib/$DYNAMIC $DEB_DIR/usr/lib/lib${LIBNAME}.so
ln -sfr $DEB_DIR/usr/lib/libpi-sock.so.$VERS $DEB_DIR/usr/lib/libpi-sock.so

# list of headers to include
HEADERS="$LIBNAME.h pi-vers.h pi-spi.h pi-i2c.h pi-sock.h MCP23017.h"
# list of man pages to include
MANPAGES="$LIBNAME.3 MCP23017.3"

cd $SOURCE
install -m 0644 $HEADERS	$DEB_DIR/usr/include/
install -m 0644 $MANPAGES	$DEB_DIR/usr/share/man/man3/
install -m 0644 -p pi_gpio.py	$DEB_DIR/usr/lib/python3/dist-packages/
install -m 0644 -p kpwm.py	$DEB_DIR/usr/lib/python3/dist-packages/
install -m 0644 -p pi_sock.py	$DEB_DIR/usr/lib/python3/dist-packages/
sudo install -o root -m 0755 -p gpioStatus	$DEB_DIR/usr/bin/
sudo install -o root -m 0755 -p pi-gpiod	$DEB_DIR/usr/bin/

# Create DEBIAN control file
cat << EOF > $DEB_DIR/DEBIAN/control
Package: $LIBNAME
Version: $VERS
Section: libraries
Priority: optional
Architecture: $ARCH
Depends: libc6
Maintainer: Ian Binnie <milliways@binnie.id.au>
Description: A dynamic C library to control Raspberry Pi GPIO channels
	includes python overlay
EOF

# Build .deb
dpkg-deb --build $DEB_DIR
