#!/bin/bash
# script to create pi-i2c deb
# 2025-06-14

# Directory containing code source
# Edit if not default
LIBNAME='pi-i2c'
PROJDIR='pi-gpio'	# project directory
# CODEDIR="$HOME/$LIBNAME"
CODEDIR="$HOME/$PROJDIR"
SOURCE="$CODEDIR/source"

# Select destination directory for deb
# default is 'dist' under $CODEDIR
DISTDIR="$CODEDIR/dist"
# Check/create DISTDIR
if [ ! -e $DISTDIR ]; then
	mkdir $DISTDIR
fi

ARCH=$(dpkg --print-architecture)

REVISION="$1"
if [ "${REVISION}" = "" ]; then
REVISION="1"
fi

VERS=$(cat $CODEDIR/VERSION)
DEB_VERSION="$VERS-$REVISION"

# Rebuild library files
CURRENT_DIR=$(pwd)
cd $SOURCE
make clean
make
cd $CURRENT_DIR

DYNAMIC="lib$LIBNAME.so.$VERS"
DEB_DIR_NAME="${LIBNAME}_${DEB_VERSION}_$ARCH"
DEB_DIR="$DISTDIR/$DEB_DIR_NAME"

# Make DEB structure
mkdir -p $DEB_DIR
# Remove any existing content
rm -rf $DEB_DIR/*

mkdir -p $DEB_DIR/usr/lib
mkdir -p $DEB_DIR/usr/include
mkdir -p $DEB_DIR/usr/share/man/man3
mkdir -p $DEB_DIR/DEBIAN
mkdir -p $DEB_DIR/usr/lib/python3/dist-packages/
mkdir -p $DEB_DIR/usr/bin

# Copy libraries
echo "Copy libraries"
cp $SOURCE/$DYNAMIC $DEB_DIR/usr/lib/

ln -sfr $DEB_DIR/usr/lib/$DYNAMIC $DEB_DIR/usr/lib/lib${LIBNAME}.so

# list of headers to include
HEADERS="$LIBNAME.h MCP23017.h"
# list of man pages to include
MANPAGES="$LIBNAME.3 MCP23017.3"
cd $SOURCE
install -m 0644 $HEADERS	$DEB_DIR/usr/include/
install -m 0644 $MANPAGES	$DEB_DIR/usr/share/man/man3/
install -m 0644 -p pi_i2c.py	$DEB_DIR/usr/lib/python3/dist-packages/

# Create DEBIAN control file
cat << EOF > $DEB_DIR/DEBIAN/control
Package: $LIBNAME
Version: $VERS
Section: libraries
Priority: optional
Architecture: $ARCH
Depends: libc6
Maintainer: Ian Binnie <milliways@binnie.id.au>
Description: A dynamic C library to control Raspberry Pi i2c channels
	includes python overlay
EOF

# Build .deb
dpkg-deb --build $DEB_DIR
